  -- Run this in the Supabase SQL Editor (https://supabase.com/dashboard/project/_/sql/new)

-- Drop existing table if recreating
-- drop table if exists dashboard_state;

create table dashboard_state (
  id bigint generated by default as identity primary key,
  key text unique not null,
  value jsonb not null default '{}',
  updated_at timestamp with time zone default now()
);

-- Enable Row Level Security
alter table dashboard_state enable row level security;

-- Allow anonymous access (safe because the anon key is restricted by RLS)
create policy "Allow anonymous select"
  on dashboard_state for select
  to anon
  using (true);

create policy "Allow anonymous upsert"
  on dashboard_state for insert
  to anon
  with check (true);

create policy "Allow anonymous update"
  on dashboard_state for update
  to anon
  using (true);

-- Index for faster lookups
create index if not exists idx_dashboard_state_key on dashboard_state (key);
