import { Sparkles } from "lucide-react"

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  ODYSSEY: "/odyssey",
  FOCUS: "/focus",
  TIMER: "/timer",
  POMODORO: "/pomodoro",
  HABITS: "/habits",
  JOURNAL: "/journal",
  LEARNING: "/learning",
  MISSIONS: "/missions",
  TIMELINE: "/timeline",
  DECISIONS: "/decisions",
  REVIEWS: "/reviews",
  BRAIN: "/brain",
  HEALTH: "/health",
  GYM: "/gym",
  WEIGHT: "/weight",
  SLEEP: "/sleep",
  STOCKS: "/stocks",
  PROJECTS: "/projects",
  OPENCODE: "/opencode",
  STUDY: "/study",
  STUDY_STATS: "/study/stats",
  STUDY_TASKS: "/study/tasks",
  STUDY_EXAMS: "/study/exams",
  STUDY_FILES: "/study/files",
  STUDY_SOUNDS: "/study/sounds",
  STUDY_COMMUTE: "/study/commute",
  VOICE: "/voice",
  BRIEFINGS: "/briefings",
  MEMORY: "/memory",
  CORRELATIONS: "/correlations",
  FUTURE: "/future",
  REPORT: "/report",
} as const

export const NAV_ITEMS = [
  { label: "Profile", path: ROUTES.PROFILE, icon: Sparkles },
]
